Vagrant.configure("2") do |config|
  config.vm.provision :puppet

  config.vm.box = "base"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.provider :virtualbox do |vb|
	 vb.customize ["modifyvm", :id, "--memory", "100"]
         vb.customize ["modifyvm", :id, "--cpus", "1"]
         vb.customize ["modifyvm", :id, "--cpuexecutioncap", "10"]
  end

  config.vm.define "a" do |a|
    a.vm.provision "shell", :path => "configure.sh", :args => "'environment.properties'"
  end

  config.vm.define "b" do |b|
    b.vm.provision "shell", :path => "configure.sh", :args => "'environment.properties'"
  end

  config.vm.define "c" do |c|
    c.vm.provision "shell", :path => "configure.sh", :args => "'environment.properties'"
  end

  config.vm.define "d" do |d|
    d.vm.provision "shell", :path => "configure.sh", :args => "'environment.properties'"
  end
end

